project:
  type: website
  output-dir: .

website:
  title: "Stanley Barrell-Kane"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "CV"
        href: cv.qmd
format:
  html:
    theme: cosmo
    toc: true




